export const colorDesigns = {
  designOne: {
    background: 'bg-sky-950',
    title: 'text-sky-700',
    subtitle: 'text-teal-400',
    paragraph: 'text-amber-400',
    text: 'text-teal-100',
    border: 'border-amber-400',
    linkBg: 'bg-teal-900',
    hov: 'bg-sky-700',
  },
  designTwo: {
    background: 'bg-orange-100',
    title: 'text-amber-400',
    subtitle: 'text-orange-600',
    paragraph: 'text-orange-950',
    text: 'text-amber-800',
    border: 'border-orange-950',
    linkBg: 'bg-amber-200',
    hov: 'bg-orange-300',
  },
  designThree: {
    background: 'bg-violet-950',
    title: 'text-purple-700',
    subtitle: 'text-violet-300',
    paragraph: 'text-purple-600',
    text: 'text-purple-100',
    border: 'border-purple-200',
    linkBg: 'bg-purple-900',
    hov: 'bg-violet-900',
  },
};
